### ISSUE TITLE
Error 404 :  NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by bishnubhatta** [mohankumarpaluru/oracle-freetier-instance-creation#34]
**Describe the bug**
The script encountered an unhandled error and exited unexpectedly.

Please re-run the script by executing './setup_init.sh rerun'.

And raise a issue on GitHub if its not already existing:
https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/issues

 And include the following error message to help us investigate and resolve the problem:

status: 404
code: NotAuthorizedOrNotFound
message: Authorization failed or requested resource not found.

**Screenshots**
![image](https://github.com/user-attachments/assets/9ec35fa3-9de1-48d4-b016-f0b42a6cfc52)
![image](https://github.com/user-attachments/assets/1dcc7868-1178-4885-a4fc-c8e25c678eca)

**Additional context**

**Comment by mohankumarpaluru** [comment]
Hi @bishnubhatta , can you please check if the oci_config file has an extra space at the end ? and also the verify if the API key file is proper,. If everything seems proper , better redo API key creation.

**Comment by bishnubhatta** [comment]
Thank you @mohankumarpaluru . I am still getting the same error. Tried deleting the API and recreating fresh one. Still hte same error

**Comment by Daryan97** [comment]
I may be a little late to answer this, but this error is most likely you wrote an invalid ID inside `oci.env` because for the last 3 hours, this happened to me, I wrote a wrong SUBNET_ID which the documentation should've been more clear about the SUBNET_ID which should be the subnet OCID, also when I removed it but it gave me no error but I ran the python script using `.env/bin/python3 main.py` telling me that the subnet ID is null and it shouldn't be null, I was tired to fix the program so I just gave it a new subnet and now the program running perfectly.

**Comment by bishnubhatta** [comment]
> I may be a little late to answer this, but this error is most likely you wrote an invalid ID inside `oci.env` because for the last 3 hours, this happened to me, I wrote a wrong SUBNET_ID which the documentation should've been more clear about the SUBNET_ID which should be the subnet OCID, also when I removed it but it gave me no error but I ran the python script using `.env/bin/python3 main.py` telling me that the subnet ID is null and it shouldn't be null, I was tired to fix the program so I just gave it a new subnet and now the program running perfectly.

Thank you @Daryan97 . Now, I got another error after fixing the subnet id:
status: 400
code: InvalidParameter
message: Invalid ssh public key type "-----BEGIN"

**Comment by Daryan97** [comment]
@bishnubhatta make sure the public key you download for the server is not invalid, I suggest you to go through "create Instance" process through OCI just once, to create subnet property and generate a private and public key for the instance, which you have to give the server the public key, but keep your private key as well, otherwise you won't be able to access the instance in the future.

If you don't want to do that, then use PuttyGen to generate public and private key. Once again, keep your keys mainly the private key, you will need it to access the instance.

**Comment by bishnubhatta** [comment]
Thank you @Daryan97 . The script is working now. However it says out of host capacity
